version: "3.9"
services:
  bot:
    image: ikeanotifier
    ports: 
      - "5000:5000"
    networks:
      - net
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - net
networks:
  net: